---
- name: Demo on Loop Control - Basic
  hosts: ciscoIOS
  gather_facts: false
  vars:
    interfaces:
      - name: Ethernet0/0
        description: Uplink to ISP
        ip_address: 10.10.10.100
        subnet_mask: 255.255.255.0

      - name: Ethernet0/1
        description: Internal Network
        ip_address: 1.1.1.1
        subnet_mask: 255.255.255.0
        
  tasks:
    - name: Print interfaces item
      ansible.builtin.debug:
        msg: 
          - " Interface name is {{ interface.name }}"
      loop: "{{ interfaces }}"
      loop_control:
        loop_var: interface
        index_var: index
        label: "item no: {{ index }} - Configuring interface {{ interface.name }} with IP {{ interface.ip_address }}"